#!/bin/sh
script_dir=$(cd $(dirname $0) ; pwd)
if [ -x $script_dir/ashlib ] ; then
  eval $($script_dir/ashlib)
else
  type ashlib >/dev/null|| exit 1
  eval $(ashlib)
fi
myphp=$(find_in_path myphp ASHLIB) || fatal "myphp: not found"
script=$(find_in_path ashcc.php ASHLIB) || fatal "ashcc.php: not found"

if [ $# -eq 0 ] ; then
  echo $myphp
  exit
fi

if [ x"$1" = x"--myphp" ] ; then
  shift
  exec $myphp "$@"
else
  exec $myphp $script "$@"
fi
