#!/bin/bash
#
#++
# = MYPHP(1)
# :Revision: 1.0
#
# == NAME
#
# myphp - PHP wrapper
#
# == SYNOPSIS
#
# *myphp* _php-script_ _[script args]_
#
# == DESCRIPTION
#
# This is my PHP wrapper script.  It does the following:
#
# * Make sure that it uses either an alternative `.ini` script or
#   disables `short_open_tag` and skips the system's `.ini` file.
# * loads some initialisation code.
# * executes user script
#
# == SEE ALSO
#
# php(1)
#
#--
set -euf -o pipefail

PHP_OPTS=()

script_dir=$(cd $(dirname "$0") && pwd)
script_name=$(basename "$0")

if [ $# -eq 0 ] ; then
  echo "$script_dir/$script_name"
  exit 1
fi

if [ -f "$script_dir/$script_name.ini" ] ; then
  PHP_OPTS+=( -c "$script_dir/$script_name.ini" )
else
  PHP_OPTS+=( -n -dshort_open_tag=Off )
fi

php_code=""

if [ -f "$script_dir/$script_name.php" ] ; then
  # Loads my PHP extensions...
  php_code="$php_code
	require_once('$script_dir/$script_name.php');"
fi

while [ $# -gt 0 ] ; do
  if [ -f "$1" ] ; then
    php_code="$php_code
	require_once('$1');"
    shift
    break
  fi
  PHP_OPTS+=( "$1" )
  shift
done

if [ -n "$php_code" ] ; then
  PHP_OPTS+=(  -r "$php_code" )
fi

exec php \
    "${PHP_OPTS[@]}" \
    -- "$@"
